# What are Tensors?

## Tensors

텐서는 배열, 행렬과 매우 유사한 데이터 구조입니다. Pytorch에서는 텐서를 사용하여 모델의 입력과 출력, 모델의 매개변수를 인코딩합니다. 

텐서는 GPU 또는 다른 하드웨어 가속기를 사용할 수 있는 점을 제외하고 [NumPy](https://numpy.org/)의 ndarrays와 유사합니다. 사실, 텐서와 Numpy 배열은 종종 동일한 메모리를 공유할 수 있으므로 데이터를 복사할 필요가 없습니다. 텐서는 또한 자동 미분에 최적화되어 있습니다(Autograd 단원에서 살펴볼 것입니다). `ndarrays`가 익숙하다면 텐서 API를 바로 살펴보고, 그렇지 않다면 아래를 따라해보시기 바랍니다. 

먼저 환경을 설정해봅시다. 

In [1]:
import torch
import numpy as np

## Initializing a Tensor
텐서는 다양한 방법으로 초기화할 수 있습니다. 

### Directly from data
텐서는 데이터를 통해 직접 생성될 수 있습니다. 데이터형은 자동으로 추론됩니다.

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

### From a NumPy array
텐서는 Numpy 배열을 통해 생성될 수 있습니다(and vice versa - see `bridge-to-np-label`). 

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

### From another tensor
새로운 텐서는 명시적으로 재정의하지 않는 한 인수의 텐서 속송(모양, 데이터 유형)을 유지합니다.

In [4]:
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.4840, 0.4708],
        [0.7626, 0.1482]])


### With random or constant values
`shape` 텐서 차원을 나타내는 튜플입니다. 아래 함수에서 출력 텐서의 차원이 결정됩니다. 

In [5]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.3313, 0.1497, 0.9364],
        [0.4669, 0.1817, 0.8417]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor
텐서의 속성에는 shape, data type과 저장된 장치가 표현됩니다.

In [6]:
tensor = torch.rand(3, 4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


## Operations on Tensors
수학, 선형대수, 행렬 연산(transposing, indexing, slicing) 등 100개 이상의 텐서 연산들이 제공되며 [여기](https://pytorch.org/docs/stable/torch.html)에서 확인 가능합니다. 각 연산은 GPU를 활용할 수 있으며 일반적으로 GPU의 연산이 더욱 빠릅니다. 텐서는 기본적으로 CPU에 생성되므로 `.to` 함수를 사용하여 명시적으로 GPU로 옮겨야 합니다(GPU가 사용가능한지 확인한 후). 큰 규모의 텐서를 장치 간에 복사하는 것은 긴 시간 및 많은 메모리 소비를 유발하므로 주의가 필요합니다. 

In [7]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
print(torch.cuda.is_available())

True


### Standard numpy-like indexing and slicing

In [8]:
tensor = torch.rand(4, 4)
print("First row: ", tensor[:, 0])
print("First column: ", tensor[0, :])
print("Last column: ", tensor[-1, :])

tensor[:, 1] = 0
print(tensor)

First row:  tensor([0.9448, 0.6379, 0.3568, 0.9430])
First column:  tensor([0.9448, 0.2119, 0.0776, 0.7960])
Last column:  tensor([0.9430, 0.2688, 0.1787, 0.8009])
tensor([[0.9448, 0.0000, 0.0776, 0.7960],
        [0.6379, 0.0000, 0.8492, 0.3812],
        [0.3568, 0.0000, 0.6712, 0.5232],
        [0.9430, 0.0000, 0.1787, 0.8009]])


### Joining tensors
`torch.cat`을 사용하면 주어진 차원을 유지하면서 순차적으로 결합할 수 있습니다.`torch.cat`와 약간 다른 결합 연산으로 `torch.stack`(차원이 증가됨, `unsqueeze(0)`+`cat`효과)을 사용할 수 있습니다.

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=0) # row-wide
print("[torch.cat]")
print(t1)

t2 = torch.stack([tensor, tensor, tensor], dim=0) # row-wide
print("[torch.stack]")
print(t2)

[torch.cat]
tensor([[0.9448, 0.0000, 0.0776, 0.7960],
        [0.6379, 0.0000, 0.8492, 0.3812],
        [0.3568, 0.0000, 0.6712, 0.5232],
        [0.9430, 0.0000, 0.1787, 0.8009],
        [0.9448, 0.0000, 0.0776, 0.7960],
        [0.6379, 0.0000, 0.8492, 0.3812],
        [0.3568, 0.0000, 0.6712, 0.5232],
        [0.9430, 0.0000, 0.1787, 0.8009],
        [0.9448, 0.0000, 0.0776, 0.7960],
        [0.6379, 0.0000, 0.8492, 0.3812],
        [0.3568, 0.0000, 0.6712, 0.5232],
        [0.9430, 0.0000, 0.1787, 0.8009]])
[torch.stack]
tensor([[[0.9448, 0.0000, 0.0776, 0.7960],
         [0.6379, 0.0000, 0.8492, 0.3812],
         [0.3568, 0.0000, 0.6712, 0.5232],
         [0.9430, 0.0000, 0.1787, 0.8009]],

        [[0.9448, 0.0000, 0.0776, 0.7960],
         [0.6379, 0.0000, 0.8492, 0.3812],
         [0.3568, 0.0000, 0.6712, 0.5232],
         [0.9430, 0.0000, 0.1787, 0.8009]],

        [[0.9448, 0.0000, 0.0776, 0.7960],
         [0.6379, 0.0000, 0.8492, 0.3812],
         [0.3568, 0.0000, 0.6712, 0

In [10]:
t3 = torch.cat([tensor.unsqueeze(0), tensor.unsqueeze(0), tensor.unsqueeze(0)], dim=0)
print(t2 == t3)

tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])


In [11]:
t5 = torch.stack([tensor, tensor, tensor], dim=1) # dim=1
print(t5)

tensor([[[0.9448, 0.0000, 0.0776, 0.7960],
         [0.9448, 0.0000, 0.0776, 0.7960],
         [0.9448, 0.0000, 0.0776, 0.7960]],

        [[0.6379, 0.0000, 0.8492, 0.3812],
         [0.6379, 0.0000, 0.8492, 0.3812],
         [0.6379, 0.0000, 0.8492, 0.3812]],

        [[0.3568, 0.0000, 0.6712, 0.5232],
         [0.3568, 0.0000, 0.6712, 0.5232],
         [0.3568, 0.0000, 0.6712, 0.5232]],

        [[0.9430, 0.0000, 0.1787, 0.8009],
         [0.9430, 0.0000, 0.1787, 0.8009],
         [0.9430, 0.0000, 0.1787, 0.8009]]])


## Arithmetic operations

In [12]:
# 행렬 곱
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[1.5324, 0.9721, 0.8057, 1.5424],
        [0.9721, 1.2733, 0.9970, 1.0586],
        [0.8057, 0.9970, 0.8515, 0.8754],
        [1.5424, 1.0586, 0.8754, 1.5627]])

In [13]:
(y1 == y2) & (y1 == y3)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [14]:
# element-wise product
z1 = tensor * tensor.T
z2 = tensor.mul(tensor.T)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor.T, out=z3)

tensor([[0.8927, 0.0000, 0.0277, 0.7507],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0277, 0.0000, 0.4505, 0.0935],
        [0.7507, 0.0000, 0.0935, 0.6414]])

In [15]:
(z1 == z2) & (z1 == z3)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Single-element tensors
아래 예제와 같이 모든 텐서의 값이 하나로 합쳐지는 경우, `item()` 함수를 사용하여 Python 숫자형 값으로 전활할 수 있습니다.

In [16]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

7.160561561584473 <class 'float'>


### In-plale operations
결과를 피연산자에 저장하는 연산을 in-place라고 합니다. 이들은 `_` 접미사로 표현됩니다. 예를 들어 `x.copy_()`, `x.t_()`는 x를 변경합니다.
> **Note:** In-place 연산은 메모리를 절약할 수는 있지만 연산 히스토리가 사라지기 때문에 문제가 될 수 있으므로 권장되지는 않습니다. 

In [17]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.9448, 0.0000, 0.0776, 0.7960],
        [0.6379, 0.0000, 0.8492, 0.3812],
        [0.3568, 0.0000, 0.6712, 0.5232],
        [0.9430, 0.0000, 0.1787, 0.8009]]) 

tensor([[5.9448, 5.0000, 5.0776, 5.7960],
        [5.6379, 5.0000, 5.8492, 5.3812],
        [5.3568, 5.0000, 5.6712, 5.5232],
        [5.9430, 5.0000, 5.1787, 5.8009]])


## Bridge with NumPy
CPU로 생성한 텐서와 NumPy 배열은 원본의 메모리 위치를 공유할 수 있으므로, 하나를 변경하면 다른 하나도 변경됩니다. 
 
### Tensor to NumPy array

In [18]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경이 Numpy 배열에도 미칩니다. 

In [19]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor

In [20]:
n = np.ones(5)
t = torch.from_numpy(n)

반대도 성립합니다.

In [21]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
