## numpy와 닮은 pytorch

In [8]:
import torch

In [9]:
a = torch.tensor([1, 2, 3, 4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])


In [10]:
b = torch.tensor([1, 2, 3.1, 4])
print(b)
print(type(b))
print(b.dtype)
print(b.shape)

tensor([1.0000, 2.0000, 3.1000, 4.0000])
<class 'torch.Tensor'>
torch.float32
torch.Size([4])


In [16]:
A = torch.tensor([[1, 2, 5], [3, 4, 5]])
print(A)
print(type(A))
print(A.dtype)
print(A.ndim)  # 차원 수
print(A.shape) # 행렬 형태
print(A.size())  # shape
print(A.numel())  # 전체 성분 수

tensor([[1, 2, 5],
        [3, 4, 5]])
<class 'torch.Tensor'>
torch.int64
2
torch.Size([2, 3])
torch.Size([2, 3])
6


In [21]:
print(torch.zeros(5))
print(torch.zeros(3, 3))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.arange(3,10,2))
print(torch.arange(0,1,0.1))
print(torch.linspace(0,1,11)) # 0에서부터 1 포함 10개로 등분



tensor([0., 0., 0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])


In [22]:
A = torch.tensor([[1, 2, 3], [1, 2, 3]])
B = torch.tensor([[4, 5, 6], [1, 1, 1]])
print(A + B)
print(A - B)
print(A * B)  # Hadamard product
print(A / B)
print(A ** 2)

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])
tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[1, 4, 9],
        [1, 4, 9]])


In [24]:
print(B.T)
print(A @ B.T)  # 행렬 곱

tensor([[4, 1],
        [5, 1],
        [6, 1]])
tensor([[32,  6],
        [32,  6]])


## 다차원 행렬의 인덱싱

In [26]:
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A[0])
print(A[-1])
print(A[1:])
print(A[0, 2])
print(A[0][2])
print(A[0, 0:3:2])
print(A[:, 2])
print(A[:][2]) # not equal to print(A[:, 2])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
tensor([1, 3])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [30]:
A = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(A)
print(A.shape)
print(A[0,1,2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([2, 3, 3])
tensor(6)


### Boolean indexing

In [34]:
A = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
print(A == 3)
print(A[A == 3])
A[A == 3] = 100
print(A)

tensor([False, False,  True, False, False, False, False, False])
tensor([3])
tensor([  1,   2, 100,   4,   5,   6,   7,   8])


In [35]:
A = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
B = torch.tensor([True, False, True, False])
print(A[B, :]) # True행만 가져옴

tensor([[1, 2],
        [5, 6]])


### Tensor indexing

In [47]:
a = torch.tensor([1, 2, 3, 4, 5])
A = a[2]
print(A)

A = a[torch.tensor(2)]
print(A)

A = a[torch.tensor([2, 3, 4])]
print(A)

A = a[torch.tensor([[2, 2, 2], [3, 3, 3]])]
print(A)  # 인덱싱된 값으로 새 행렬을 만듬

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
A = a[torch.tensor([[0, 1], [1, 1]])]  # 차원이 늘어나면서 표현됨, [0]은 [1, 2, 3]을 내포함
print(A)



tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


## pytorch 함수

In [51]:
A = torch.randn(3, 3)  # normal
B = torch.rand(3, 3)  # uniform
print(A)
print(B)
print(A[A[:, 0]<0, :]) # 0 번째 열이 음수인 행

tensor([[ 1.5515, -0.4081, -1.5469],
        [-0.0956,  0.4713,  0.9904],
        [-0.5527, -0.3118, -0.4483]])
tensor([[0.1403, 0.1156, 0.5282],
        [0.7838, 0.2832, 0.0523],
        [0.3552, 0.7676, 0.5870]])
tensor([[-0.0956,  0.4713,  0.9904],
        [-0.5527, -0.3118, -0.4483]])


In [61]:
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(torch.abs(A)))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1))))  # tensor 형만 인수로 사용할 수 있음
print(torch.log10(torch.abs(A)))
print(torch.log2(torch.abs(A)))
print(torch.round(A))
print(torch.round(A, decimals=2))
print(torch.floor(A))
print(torch.ceil(A))

tensor([[ 1.5515, -0.4081, -1.5469],
        [-0.0956,  0.4713,  0.9904],
        [-0.5527, -0.3118, -0.4483]])
tensor([[1.5515, 0.4081, 1.5469],
        [0.0956, 0.4713, 0.9904],
        [0.5527, 0.3118, 0.4483]])
tensor([[1.2456, 0.6388, 1.2438],
        [0.3092, 0.6865, 0.9952],
        [0.7434, 0.5584, 0.6696]])
tensor([[4.7187, 1.5039, 4.6970],
        [1.1003, 1.6021, 2.6923],
        [1.7379, 1.3659, 1.5657]])
tensor([[ 0.4392, -0.8964,  0.4363],
        [-2.3474, -0.7522, -0.0096],
        [-0.5930, -1.1654, -0.8023]])
tensor(1.)
tensor([[ 0.1908, -0.3893,  0.1895],
        [-1.0195, -0.3267, -0.0042],
        [-0.2575, -0.5061, -0.3484]])
tensor([[ 0.6337, -1.2932,  0.6294],
        [-3.3867, -1.0851, -0.0139],
        [-0.8555, -1.6814, -1.1574]])
tensor([[ 2., -0., -2.],
        [-0.,  0.,  1.],
        [-1., -0., -0.]])
tensor([[ 1.5500, -0.4100, -1.5500],
        [-0.1000,  0.4700,  0.9900],
        [-0.5500, -0.3100, -0.4500]])
tensor([[ 1., -1., -2.],
        [-1.,  0., 

In [66]:
print(torch.sin(torch.tensor(torch.pi/6)))
print(torch.cos(torch.tensor(torch.pi/6)))
print(torch.tan(torch.tensor(torch.pi/6)))
print(torch.tanh(torch.tensor(torch.pi/6)))

print(type(torch.pi))
print(type(torch.pi * torch.tensor(3)))  # tensor로 자동 바뀜

tensor(0.5000)
tensor(0.8660)
tensor(0.5774)
tensor(0.4805)
<class 'float'>
<class 'torch.Tensor'>


In [70]:
print(torch.log(torch.tensor(-1)))  # 실수가 아님
print(torch.isnan(torch.tensor([1, 2, torch.nan, 3, 4])))  
print(torch.isinf(torch.tensor([1, 2, torch.inf, 3, 4])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False,  True, False, False])
