# 간단한 인공신경망 만들기

In [1]:
import torch
from torch import nn

In [2]:
x = torch.tensor([1.])
model = nn.Linear(1, 1)  # 입력 node 한 개, 출력 node 한 개

print(model.weight) # 랜덤한 값이 설정됨
print(model.bias)

y = model(x)
print(y)

y = x @ model.weight + model.bias
print(y)

Parameter containing:
tensor([[0.6024]], requires_grad=True)
Parameter containing:
tensor([0.8804], requires_grad=True)
tensor([1.4828], grad_fn=<AddBackward0>)
tensor([1.4828], grad_fn=<AddBackward0>)


In [3]:
fc1 = nn.Linear(1, 3)
fc2 = nn.Linear(3, 1)

print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)

x = torch.tensor([1.])
x = fc1(x)
print(x)
x = fc2(x)
print(x)

x = torch.tensor([1.])
y = (x@fc1.weight.T+fc1.bias)@fc2.weight.T+fc2.bias
print(y)

Parameter containing:
tensor([[-0.4480],
        [ 0.5655],
        [-0.8771]], requires_grad=True)
Parameter containing:
tensor([-0.5085, -0.8723, -0.2466], requires_grad=True)
Parameter containing:
tensor([[ 0.1425, -0.2715, -0.4800]], requires_grad=True)
Parameter containing:
tensor([-0.1932], requires_grad=True)
tensor([-0.9564, -0.3068, -1.1237], grad_fn=<AddBackward0>)
tensor([0.2932], grad_fn=<AddBackward0>)
tensor([0.2932], grad_fn=<AddBackward0>)


In [4]:
# nn.Linear는 개*채*행*열 에서 "채" 형태로 (1D data) 들어오길 기대하는 녀석이다.
# 즉, 노드 하나가 곧 한 채널을 의미한다.
# 따라서, 데이터 여러 개를 통과시키고 싶다면 개*채의 형태로 줘야 함
# 일단, wieght shape 개*채에서 채는 무조건 앞에 챈러 개수와 맞춰야 하는 룰을 설정함


In [5]:
fc1 = nn.Linear(1, 3)
fc2 = nn.Linear(3, 1)

model = nn.Sequential(fc1, fc2)
x = torch.tensor([1.])
print(model(x))

tensor([-0.0310], grad_fn=<AddBackward0>)


In [6]:
x = torch.randn(5, 2)
model = nn.Sequential(
    nn.Linear(2, 5),
    nn.Linear(5, 10),
    nn.Linear(10, 3)
)
print(x)
print(model(x))



tensor([[-0.9686,  1.0229],
        [-0.8387,  1.7444],
        [ 0.4021,  2.5025],
        [-0.7557, -0.9301],
        [-0.3789,  0.3056]])
tensor([[ 0.6180, -0.3130,  0.0989],
        [ 0.6306, -0.4186,  0.0777],
        [ 0.4590, -0.4413,  0.0039],
        [ 0.4895,  0.0180,  0.1299],
        [ 0.4852, -0.1506,  0.0864]], grad_fn=<AddmmBackward0>)


In [7]:
x = torch.randn(2, 3, 1, 5, 2)  # 마지막 수만 채널로 인식하면 됨
print(x)
print(model(x))  

tensor([[[[[ 0.4402, -1.0430],
           [ 0.7390, -1.8498],
           [-0.8796,  0.4701],
           [-1.9337, -0.8524],
           [ 0.6833,  0.6768]]],


         [[[ 0.5828, -0.4236],
           [-2.0814, -0.2875],
           [-0.8140, -0.2724],
           [ 0.5366,  0.1097],
           [-0.6774,  0.1332]]],


         [[[ 0.3151,  0.0846],
           [-1.6751, -0.6262],
           [-0.3602, -1.4557],
           [-0.4994,  0.7028],
           [-0.1657,  0.3837]]]],



        [[[[-0.1699, -1.2068],
           [ 0.4641,  0.7964],
           [ 1.9145, -0.6428],
           [ 1.1025,  0.7450],
           [ 1.1609, -3.1561]]],


         [[[ 0.2850, -1.0908],
           [-1.2163,  0.2235],
           [ 0.0694, -1.8126],
           [ 2.0916, -0.2447],
           [-0.4010,  0.3874]]],


         [[[-0.5592, -1.1089],
           [ 0.3010,  1.1065],
           [-1.1650, -0.0117],
           [ 1.4683, -0.2106],
           [-1.4642,  1.5526]]]]])
tensor([[[[[ 2.8387e-01,  1.3174e-01,  7.652

# 클래스로 만들기

In [9]:
class MyModel(nn.Module):
    
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 5)
        self.fc2 = nn.Linear(5, 10)
        self.fc3 = nn.Linear(10, 3)
        self.sig1 = nn.Sigmoid()
        self.sig2 = nn.Sigmoid()
        self.sig3 = nn.Sigmoid()
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.sig1(x)
        x = self.fc2(x)
        x = self.sig2(x)
        x = self.fc3(x)
        x = self.sig3(x)                
        return x

model = MyModel()
x = torch.randn(5, 2)
y = model(x)
print(y)

tensor([[0.4202, 0.5203, 0.4760],
        [0.4182, 0.5227, 0.4766],
        [0.4210, 0.5177, 0.4759],
        [0.4182, 0.5160, 0.4774],
        [0.4220, 0.5244, 0.4749]], grad_fn=<SigmoidBackward0>)


In [10]:
print(model)

MyModel(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
  (sig1): Sigmoid()
  (sig2): Sigmoid()
  (sig3): Sigmoid()
)


In [11]:
print(model.fc1.weight)
print(model.fc2.bias)

Parameter containing:
tensor([[-0.3501,  0.5127],
        [ 0.3681, -0.2958],
        [-0.1568, -0.7006],
        [-0.4459, -0.0820],
        [-0.3342, -0.3811]], requires_grad=True)
Parameter containing:
tensor([ 0.3994,  0.3898,  0.3543,  0.3296, -0.0302,  0.1301, -0.1798,  0.3218,
        -0.2978, -0.4342], requires_grad=True)


In [ ]:
class MyModel(nn.Module):
    
    def __init__(self):
        super().__init__()
        self.fcn = nn.Sequential(
            nn.Linear(2, 5),
            nn.Sigmoid(),
            nn.Linear(5, 10),
            nn.Sigmoid(),
            nn.Linear(10, 3),
            nn.Sigmoid(),
        )
        
    def forward(self, x):
        return self.fcn

model = MyModel()
x = torch.randn(5, 2)
y = model(x)
print(y)